Spring boot and liquibase guide
Amplicode/amplicode-tutorials pull request #3
Opened 2024-06-03 03:49 UTC by irinaponomarevahaulmont

Please review

2024-06-03 05:09 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +Для удобного взаимодействия с PostgreSQL желательно наличие сервиса pgAdmin. Amplicode предлагает pgAdmin в списке рекомендуемых сервисов, так как видит сервис PostgreSQL в текущем файле. Чтобы воспо
Оно не то что бы желательно просто было бы здорово и удобно. Поэтому я бы написал что-то типо "было бы здорово также иметь и pgAdmin сервис"

2024-06-03 05:10 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +* Пометьте чекбокс **Configure DB server connections**
Мне кажется лучше будет "Выберите", ну или "Отметьте"

2024-06-03 05:47 UTC, honest-niceman requested changes
Первое ревью

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +Для удобного взаимодействия с PostgreSQL желательно наличие сервиса pgAdmin. Amplicode предлагает pgAdmin в списке рекомендуемых сервисов, так как видит сервис PostgreSQL в текущем файле. Чтобы воспо
Оно не то что бы желательно просто было бы здорово и удобно. Поэтому я бы написал что-то типо "было бы здорово также иметь и pgAdmin сервис"

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +* Пометьте чекбокс **Configure DB server connections**
Мне кажется лучше будет "Выберите", ну или "Отметьте"

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +На данный момент база данных находится в том же состоянии, что и JPA модель. Переходим к решению поставленной задачи.
Пока до сюда дочитал, забыл уже какую задачу решаем. Предлагаю явно тут указать что переходим к подключению Liquibase к нашему приложению

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +Первый чекбокс автоматически перенаправит нас к окну генерации скрипта базы данных. Благодаря второму чекбоксу Amplicode выполнит команду Liquibase `changelog-sync`, которая позволит отметить скрипты
Благодаря выбору первого чекбокса...

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +Первый чекбокс автоматически перенаправит нас к окну генерации скрипта базы данных. Благодаря второму чекбоксу Amplicode выполнит команду Liquibase `changelog-sync`, которая позволит отметить скрипты
сразу после генерации скриптов инициализации базы данных. Эта команда позволит отметить...

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +Первый чекбокс автоматически перенаправит нас к окну генерации скрипта базы данных. Благодаря второму чекбоксу Amplicode выполнит команду Liquibase `changelog-sync`, которая позволит отметить скрипты
всё что в них будет описано, наверное (скриптов же еще нет)

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +
Давай еще тут упомянем, что для прохождения этого гайда можно перейти в репозиторий с гайдами (https://github.com/Amplicode/amplicode-tutorials) и проследовать инструкции (https://github.com/Amplicode/amplicode-tutorials/blob/main/liquibase-and-spring-boot/README.md) (добавлю сюда инструкцию как удобно можно стартовать с init коммита) для настройки проекта и дальнейшего прохождения по описанному ниже

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +* Amplicode добавит необходимые зависимости и свойства в `application.properties`, сгенерирует файл `db.changelog-master.xml` и начнет процесс генерации скрипта инициализации базы данных. В открывшем
зависимости добавит в build.gradle

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +По результатам выполнения Amplicode сохранит changelog по указанному пути и выполнит команду `changelog-sync`, т.к. ранее был отмечен соответствующий checkbox.
где-то по-русски чекбокс, где то по английский

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> + * Измените кардинальность ассоциации на "многие ко многим". Amplicode предупредит, что текущая реализация может быть неоптимальной в плане производительности и предложит сгенерировать реализацию мет
Тут надо отметить, что Amplicode уже выбрал наиболее оптимальный тип для ассоциации "многие ко многим" – Set, но для полностью корректной работы Set с JPA сущностями также необходимо чтобы у неё были корректно переопределены методы equals и hashCode. Amplicode знает об этом, и предупреждает, что текущая реализация...

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +Теперь необзодимо сгенерировать для сущности `Comment` новый базовый атрибут `text`, а также создать отношение "многие к одному" с сущностью `User`. Для этого:
очепятка

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +* Вызовите всплывающее окно **Generate**, нажав **Alt+Insert** или **⌘+N** для macOS.
для Windows/Linux

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +Amplicode автоматически разместил этот скрипт в данную секцию, т.к. создание индекса может быть довольно дорогостоящей операцией, а его добавление на уровне JPA модели не является довольно распростра
Тут что-то упущено

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +Хорошей практикой при разработке Spring Boot приложения и использованием системы версионирования баз данных является применение возможностей валидации соответствия JPA модели и схемы базы данных при
Hibernate

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +Хорошей практикой при разработке Spring Boot приложения и использованием системы версионирования баз данных является применение возможностей валидации соответствия JPA модели и схемы базы данных при
`spring.jpa.hibernate.ddl-auto`

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +Внесите отмеченный красной рамкой код в файл `application-properties`:
Тут можно сказать "начните печатать ddl-auto и Amplicode предложит вам соответствующее свойства. Достаточно будет выбрать его из выпадающего списка и нажать enter"

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +Подводя итог, все поставленные в данном гайде задачи успешно выполнены менее чем за 15 минут. Вы можете установить Amplicode уже сейчас и применить полученные знания на практике.
там время прочтения 20 минут заявлено, давай и там и там одинаковое какое то значение напишем

2024-06-03 05:47 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +Подводя итог, все поставленные в данном гайде задачи успешно выполнены менее чем за 15 минут. Вы можете установить Amplicode уже сейчас и применить полученные знания на практике.
Как будто и так должны были повторять, раз читали до сюда) Давай лучше заключение напишем отталкиваясь от поставленных задач. Что научились подключать, писать скрипты версионировани и тд.

2024-06-04 10:42 UTC, irinaponomarevahaulmont commented
Готово к второму ревью.

2024-06-18 08:18 UTC, honest-niceman reviewed
По картинкам

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/liquibase-and-spring-boot.md
> +* Измените кардинальность ассоциации на "многие ко многим". Amplicode уже выбрал наиболее оптимальный тип для ассоциации "многие ко многим" — `Set`, но для полностью корректной работы `Set` с JPA сущ
предлагает?

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/amplicode-explorer-icon.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/check-boxes.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/change-preview-window.png
Скрин в плохом качестве

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/choose-db.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/choose-liquibase.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/configure-db-server-connections.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/create-new-db-connection.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/diff-changes.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/docker-compose.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/drop-index.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/email-mandatory.png
На скрине было бы хорошо обвести то, что появилось после нажатия на чекбокс

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/generate.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/inlay.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/liquibase-diff-changelog.png
Очень плохое качество

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/move-scripts.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/red-and-yellow.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/run-all-services.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/run-application.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/script-preview.png
Давай весь файл заскриним

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/select-scripts-user.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/spring-data-jpa.png
Слишком мелко. Надо сделать крупно, а нужный элемент обвести

2024-06-18 08:18 UTC, honest-niceman commented on liquibase-and-spring-boot/text-based-guide/images/youtube-thumbnail.png
Надо норм качество картинки было попросить, я бы скинул

2024-06-20 11:55 UTC, honest-niceman commented
@irinaponomarevahaulmont, нужно посмотреть гайд на сайте и поправить в соответствии с тем, что я поправил: https://amplicode.ru/guides/liquibase-spring-boot-nastroika-i-napisanie-migracii-baz-dannyh/

2024-06-26 07:29 UTC, irinaponomarevahaulmont commented
Сделала как на сайте, можно мержить в главный.

2024-07-01 13:08 UTC, honest-niceman approved these changes

2024-07-01 13:09 UTC, merged